set(board_requires torget_app esp_lcd esp_driver_gpio esp_driver_i2c esp_driver_spi)
if(TORGET_BOARD STREQUAL "waveshare_18_v2")
    list(APPEND board_requires waveshare__esp32_s3_touch_amoled_1_8)
elseif(TORGET_BOARD STREQUAL "waveshare_216")
    list(APPEND board_requires waveshare__esp32_s3_touch_amoled_2_16)
elseif(TORGET_BOARD STREQUAL "waveshare_241_v2")
    list(APPEND board_requires esp_lcd_sh8601 esp_lcd_touch_ft5x06 esp_io_expander_tca9554)
endif()

idf_component_register(SRCS "board.c" INCLUDE_DIRS "." REQUIRES ${board_requires})
