# One explicit board selector for firmware and the native LVGL simulator.
set(TORGET_BOARD "waveshare_216" CACHE STRING "VibePulse board profile")
set_property(CACHE TORGET_BOARD PROPERTY STRINGS waveshare_216 waveshare_241_v2 waveshare_191_touch waveshare_175 waveshare_18_v2)
if(TORGET_BOARD STREQUAL "waveshare_175")
  add_compile_definitions(TORGET_BOARD_175=1)
elseif(TORGET_BOARD STREQUAL "waveshare_241_v2")
  add_compile_definitions(TORGET_BOARD_241_V2=1)
elseif(TORGET_BOARD STREQUAL "waveshare_191_touch")
  add_compile_definitions(TORGET_BOARD_191_TOUCH=1)
elseif(TORGET_BOARD STREQUAL "waveshare_18_v2")
  add_compile_definitions(TORGET_BOARD_18_V2=1)
elseif(NOT TORGET_BOARD STREQUAL "waveshare_216")
  message(FATAL_ERROR "V1 is not supported. Unsupported TORGET_BOARD: ${TORGET_BOARD}. Choose waveshare_216, waveshare_241_v2, waveshare_191_touch waveshare_175 or waveshare_18_v2.")
endif()

option(TORGET_BOARD_DIAGNOSTIC "Static display and four-corner touch diagnostic" OFF)
if(TORGET_BOARD_DIAGNOSTIC)
  if(TORGET_BOARD STREQUAL "waveshare_18_v2")
    message(FATAL_ERROR "The 1.8 V2 native diagnostic is not implemented; do not use the 1.91 diagnostic for its corner sweep.")
  endif()
  add_compile_definitions(TORGET_BOARD_DIAGNOSTIC=1)
endif()
